[package]
name = "snmp2"
version = "0.2.2"
edition = "2021"
description = "SNMP client library"
authors = ["Serhij S. <div@altertech.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/roboplc/snmp2"
readme = "README.md"
keywords = ["networking", "snmp", "monitoring"]
